name: Sleep for 1 minute

on:
  merge_group:

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Redocly Registry (merge-queue-test/1) validation
    - run: |
          echo pass-validation
          exit 0
