name: Skip Redocly Registry Checks

on:
  merge_group:
    types: [checks_requested]

jobs:
  skip_redocly_registry_checks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Skip Redocly Registry Validation and Bundle Checks
        if: ${{ github.event.pull_request.head.repo.full_name == 'Redocly Registry' && github.event.pull_request.head.ref == 'merge-queue-test/1' }}
        run: |
          exit 0
